# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_auto_20160224_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patchbank',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
