# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_auto_20160224_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patch',
            options={'verbose_name_plural': 'patches'},
        ),
        migrations.AlterField(
            model_name='patch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patchbank',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patch_banks', to=settings.AUTH_USER_MODEL),
        ),
    ]
